---
- name: Update and Upgrade System
  hosts: localhost
  become: yes  # Run tasks with elevated privileges
  tasks:
    - name: Update && Upgrade packages
      apt:
        update_cache: yes
        upgrade: yes
        autoremove: yes
        autoclean: yes

    - name: Install unattended-upgrades package
      apt:
        name: unattended-upgrades
        state: present

    - name: Configure unattended-upgrades
      lineinfile:
        path: /etc/apt/apt.conf.d/20auto-upgrades
        line: |
          APT::Periodic::Update-Package-Lists "1";
          APT::Periodic::Download-Upgradeable-Packages "1";
          APT::Periodic::AutocleanInterval "7";
          APT::Periodic::Unattended-Upgrade "1";

    - name: Ensure unattended-upgrades is enabled
      systemd:
        name: unattended-upgrades
        enabled: yes
        state: started